"""String constants for SafeDocument metadata keys written by use_cases.py."""

REQUESTED_MODE = "requested_mode"
INFLIGHT_DEDUPLICATED = "inflight_deduplicated"
INFLIGHT_SHARED_COUNT = "inflight_shared_count"
CACHE_HIT = "cache_hit"
AUTO_MODE_USED = "auto_mode_used"
AUTO_MODE_REASON = "auto_mode_reason"
FAST_MODE_TOKENS = "fast_mode_tokens"
FAST_MODE_RENDER_FALLBACK = "fast_mode_render_fallback"
FAST_MODE_RENDER_FALLBACK_REASON = "fast_mode_render_fallback_reason"
FAST_MODE_RENDER_FALLBACK_ERROR = "fast_mode_render_fallback_error"
EFFECTIVE_MODE = "effective_mode"
DEGRADED_RENDER_FALLBACK = "degraded_render_fallback"
DEGRADED_REASON = "degraded_reason"
OPERATIONAL_FLAGS = "operational_flags"
FETCH_METADATA = "fetch_metadata"
RENDER_HINT = "render_hint"
RENDER_HINT_REASON = "render_hint_reason"
SCREENSHOT_TEMP = "screenshot_temp"
COST_UNITS_USED = "cost_units_used"
RENDER_COST_BUDGET = "render_cost_budget"
